### ISSUE TITLE
Debate transcript blog post not displaying properly

### ISSUE THREAD

**Issue by kbenoit** [quanteda/blog.quanteda.org#18]
I'm not exactly sure why, but the blog post https://blog.quanteda.org/1/01/01/ is not displaying properly. I suspect this is something about how we (I) processed the Rmd into md, but the date is wrong and there is no title. This happened when I accepted PR #14.

Can someone please fix this asap? And update the instructions on the `README.md` about how this should be handled in the future. Thanks!

**Comment by stefan-mueller** [comment]
Maybe @amatsuo knows how to deal with this because you wrote the first two posts?

**Comment by kbenoit** [comment]
Solved in fc9ad2a
